# @package _global_
defaults:
  - /dataset/Nuscenes_map_cache_box_small_with_lidar
  # - /runner/8gpus
  - model: ../../model/SDV1.5mv_rawbox_with_lidar
  - _self_  # make sure override

task_id: 224x400

log_root_prefix: ./with_lidar_version_01
log_root: ./with_lidar_version_01
resume_from_checkpoint: null

use_lidar: true

runner:
  num_train_epochs: 350
  validation_show_box: true
  enable_xformers_memory_efficient_attention: true  # always need this.
  bbox_add_ratio: 0.1

